# Generated by Django 3.2 on 2021-04-20 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('subtitle', models.CharField(max_length=30)),
                ('job_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='profile/')),
                ('address', models.CharField(max_length=30)),
                ('provenece', models.CharField(max_length=30)),
                ('working_hour', models.IntegerField()),
                ('number', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField(max_length=30)),
                ('working_time', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
